version: '3'
services:
  mongodb:
    build: .
    ports:
     - "8000:27107"
    volumes:
     - d:\appdata:c:\test
  mssql:
   build: .\mssql
   ports:
     - 1400:1433
  volumes:
     - d:\mssqldata:c:\mssqldata